[lint]
select = ["I", "TC", "BLE", "C901", "SIM", "UP", "PYI", "C4", "B", "W", "TRY", "RUF", "T"]
ignore = ["TRY003"]

[lint.mccabe]
max-complexity = 25

[lint.isort]
force-sort-within-sections = true
known-first-party = ["homeassistant", "tests", "custom_components"]
combine-as-imports = true
forced-separate = ["tests"]
